version: 0.2

phases:
  build:
    commands:
      # - npm install
      # - npm run build
      
      # This is not working. Workaround under
      - export HOME='/tmp' 
      - rm -rf ./node_modules
      - npm install --production
artifacts:
  files: 
    - '**/*'
