version: 0.2

phases:
  build:
    commands:
      # - npm install
      # - npm run build
      
      # This is not working. Workaround under
      # - npm install --production
      - rm -rf ./node_modules
      - npm install --production
      - rm -rf ./node_modules/sqlite3
      - export LDFLAGS="-L/usr/local/lib"
      - export CPPFLAGS="-I/usr/local/include -I/usr/local/include/sqlcipher"
      - export CXXFLAGS="$CPPFLAGS"
      - npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose
      - node -e 'require("sqlite3")'
artifacts:
  files: 
    - '**/*'
