version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm run sqlite-build
  post_build:
    commands:
      - zip -r lambda.zip *
artifacts:
  files: 
    - lambda.zip
    - swagger.json
