version: 0.2

phases:
  build:
    commands:
      # - npm install
      # - npm run build
      
      # This is not working. Workaround under
      # - npm install --production
      - rm -rf ./node_modules
      - npm install --production
      - rm -rf ./node_modules/sqlite3
      - npm install --build-from-source sqlite3
artifacts:
  files: 
    - '**/*'
